import { Head } from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import DefaultLayout from "../../layouts/Default";
export default function Cat() {
  const [cat, setCat] = useState(null);
  const router = useRouter();
  const { id } = router.query;

  const fetchCat = async () => {
    const res = await fetch(`/api/cats/${id}`);
    const data = await res.json();
    setCat(data);
  };

  useEffect(() => {
    fetchCat();
  }, []);
  return (
    <div>
      <DefaultLayout>
        <Head>
          <title>{cat.name}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {cat && (
          <div className="container mt-5" style={{ display: "flex" }}>
            <img src={cat.image.url} alt={cat.image.alt} className="w-50" />
            <div className="mx-5">
              <h1>{cat.name}</h1>
              <p>{cat.description}</p>
            </div>
          </div>
        )}
      </DefaultLayout>
    </div>
  );
}
